### ISSUE TITLE
如何在 issue 中引用 issue？

### ISSUE THREAD

**Issue by lufg** [lufg/KPM#3]
issues经常是独立于其他issues的，或者至少与其他有关系而且你想将它们连接起来。你可以通过输入井号(#)+issue编号来引用issues。

Hey @kneath, I think the problem started in #42

如果你想包含其他仓库的issues，你可以在前面加上仓库的名字，比如像这样：

kneath/example-project#42

有一种引用issues的更有趣的方式就是直接从commits中引用issues。你可以在提交信息中包含issue编号。

* [熟练使用Issues - CSDN博客](http://blog.csdn.net/github_30605157/article/details/52837864)

**Comment by lufg** [comment]
#1

**Comment by rickyes** [comment]
#10

**Comment by linchutao** [comment]
#1

**Comment by codewangg** [comment]
#2

**Comment by jiangtao69039** [comment]
#1

**Comment by jiangtao69039** [comment]
> #1

#2

**Comment by COCONUTwwater** [comment]
#1

**Comment by haiwang2517** [comment]
`test code
hello word`

**Comment by InjoyDeng** [comment]
djberg96/sys-filesystem#66

**Comment by kyle-kw** [comment]
openai/tiktoken#80

**Comment by kaysonyu** [comment]
#1

**Comment by Zionshang** [comment]
#1

**Comment by xjw580** [comment]
[如何设置 issue 分类标签和时限 #2](https://github.com/lufg/KPM/issues/2)

**Comment by xjw580** [comment]
#2

**Comment by xjw580** [comment]
@mentions #2

**Comment by kankj** [comment]
#1

**Comment by kankj** [comment]
#1

**Comment by xjw580** [comment]
![S50405-16114722_com.github.android.png](https://github.com/user-attachments/assets/1825ec32-d4aa-45c0-b42c-93dd24b185fc)

如何这样引用issue

**Comment by xjw580** [comment]
![S50405-16114722_com.github.android.png](https://github.com/user-attachments/assets/637d5734-a08f-4a7b-8619-80d5b4dd6ea9)

如何这样引用issue

**Comment by ZhangXiChang** [comment]
seanmonstar/reqwest#2720

**Comment by k5746** [comment]
@xjw580 This means that this issue has been referenced elsewhere. In other words, this prompt message appears in the referenced issue.

**Comment by k5746** [comment]
@xjw580 This means that this issue has been referenced elsewhere. In other words, this prompt message appears in the referenced issue.
